version: "3.7"

services:
    web:
        image: nginx:1.17
        ports:
            - 80:80
        volumes:
            - ./code:/var/www/html
            - ./setup/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    php:
        build:
            context: .
        volumes:
            - ./code:/var/www/html
        links:
            - db:db.local
    
    db:
        image: mysql:5.6
        volumes:
            - ./persist/mysql:/var/lib/mysql
            - ./persist/sql.d:/sql.d
        environment:
            - MYSQL_ROOT_PASSWORD=poop